@startuml ExampleUse
title Example use

actor "John Doe" as John
participant "John Doe's computer" as JohnPC
participant "Sequencer Server" as server
participant "Jane Doe's computer" as JanePC
actor "Jane Doe" as Jane

John -> JohnPC: initialize
loop 5
    John -> JohnPC: addInstrument
    activate JohnPC
    JohnPC -> John:updateInstrumentAlternatives
    deactivate JohnPC
end
group Create Track [until track is finished]
    John -> JohnPC: toggleSixteenth
end
John -> JohnPC: editTrackName
John -> JohnPC: editArtistName
John -> JohnPC: saveTrack
activate JohnPC


JohnPC -> server: saveTrack
activate server
server -> JohnPC: HTTP response: 201 Created
deactivate server
JohnPC -> John: displayStatusMsg
deactivate JohnPC

John -> Jane: "Check out track"
Jane -> JanePC: openTrackLoaderModal
activate JanePC
JanePC -> Jane: Modal Opened
deactivate JanePC
Jane -> JanePC: filterTracks
activate JanePC

JanePC -> server: fetchTracks
activate server
server -> JanePC: Tracks in HTTP body
deactivate server

JanePC -> Jane: Show list of\n tracks matching search
deactivate JanePC
Jane -> JanePC: loadTrack
activate JanePC
JanePC -> Jane: updateElements
deactivate JanePC
@enduml